#!/usr/bin/env bash

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     installer=sudo apt;;
    Darwin*)    installer=brew;;
esac

if ! command -v zsh >/dev/null; then
	echo "Installing zsh"
  ${installer} install zsh
fi

if [[ ! -d ~/.oh-my-zsh ]]; then
	echo "Installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

if [[ ! -d ~/.oh-my-zsh/custom/themes/powerlevel10k ]]; then
  echo "Installing Powerlevel10k"
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
fi

if ! which fzf >/dev/null; then
	echo "Installing fzf"
  ${installer} install fzf
#  "$(brew --prefix)"/opt/fzf/install
fi

if ! which rcup >/dev/null; then
	echo "Installing rcm"
  ${installer} install rcm
fi

if ! which tmux >/dev/null; then
	echo "Installing tmux"
  ${installer} install tmux
fi

echo "symlinking these files:"
lsrc -x install
rcup -x install
